import streamlit as st
from groq import Groq

# वेबसाइट का मुख्य सेटअप
st.set_page_config(page_title="My Custom ChatGPT", page_icon="🤖", layout="centered")
st.title("My Custom ChatGPT 🤖")
st.caption("Powered by Llama3 Core & Flux Engine | 5 Free Images Daily")

# आपकी सुरक्षित Groq API Key
GROQ_API_KEY = "gsk_beIvf0Wbws2qE0OlYMMuWG3dyb3FYSB2jNYQ2TlO4QghwG49C1Lm9"
client = Groq(api_key=GROQ_API_KEY)

# चैट और इमेज मेमोरी सेटअप
if "messages" not in st.session_state:
    st.session_state.messages = []
if "image_count" not in st.session_state:
    st.session_state.image_count = 0

# पुरानी बातचीत स्क्रीन पर लोड करें
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message.get("is_image"):
            st.image(message["content"], caption="Generated by Flux Model", width="stretch")
        else:
            st.markdown(message["content"])

# नीचे वाला चैट इनपुट बॉक्स
if user_prompt := st.chat_input("Ask me anything or type '/image [prompt]' for photos..."):
    
    with st.chat_message("user"):
        st.markdown(user_prompt)
    st.session_state.messages.append({"role": "user", "content": user_prompt})

    with st.chat_message("assistant"):
        # अगर यूज़र इमेज बनाना चाहता है
        if user_prompt.startswith("/image"):
            if st.session_state.image_count >= 5:
                st.error("🛑 Daily free limit reached! Upgrade to Pro for unlimited images or pay ₹9 via UPI.")
            else:
                st.session_state.image_count += 1
                image_prompt = user_prompt.replace("/image", "").strip()
                # प्रॉम्प्ट को सही फॉर्मेट में बदलने का बिल्कुल सही तरीका
                encoded_prompt = image_prompt.replace(" ", "%20")
                real_image_url = f"https://pollinations.ai{encoded_prompt}?enhance=true"
                
                # स्क्रीन पर फोटो दिखाने का बिल्कुल लेटेस्ट तरीका
                st.image(real_image_url, caption=f"Images remaining today: {5 - st.session_state.image_count}", width="stretch")
                st.session_state.messages.append({"role": "assistant", "content": real_image_url, "is_image": True})
        
        # अगर यूज़र सामान्य बातचीत करना चाहता है
        else:
            try:
                completion = client.chat.completions.create(
                    model="openai/gpt-oss-120b",
                    messages=[
                        {"role": "system", "content": "You are a helpful AI assistant like ChatGPT. Speak in the language preferred by the user."},
                        *st.session_state.messages
                    ]
                )
                ai_response = completion.choices[0].message.content
                st.markdown(ai_response)
                st.session_state.messages.append({"role": "assistant", "content": ai_response})
            except Exception as e:
                st.error(f"Error connecting to AI brain: {str(e)}")
